name: Deploy P4TG API Docs

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Controller to generate OpenAPI JSON
        run: cd Controller && cargo run || exit 0

      - name: Create doc folder
        run: mkdir doc

      - name: Move openapi.json into place
        run: mv Controller/openapi.json doc/openapi.json

      - name: Clone swagger UI
        run: git clone https://github.com/swagger-api/swagger-ui.git

      - name: Move swagger UI into place
        run: mv swagger-ui/dist doc/dist/ && mv doc/dist/index.html doc/index.html && mv doc/dist/index.css doc/index.css

      - name: Replace dynamic Swagger UI URL
        run: |
            sed -ie 's/url:.*$/url: "\.\/openapi\.json",/' doc/dist/swagger-initializer.js

      - name: Fix Swagger UI Paths
        run: |
            sed -i 's/href="\./href=".\/dist/g' doc/index.html && sed -i 's/src="\./src=".\/dist/g' doc/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc