name: Data plane build

on:
  push:
    branches: [ "main", "nightly"]
  pull_request:
    branches: [ "main", "nightly"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fihle/open-p4studio:9.13.4
      env:
        SDE: /open-p4studio
        SDE_INSTALL: /open-p4studio/install

    steps:
      - uses: actions/checkout@v3
      - name: Tofino1 CI
        run: cd P4-Implementation && sudo -E /open-p4studio/install/bin/bf-p4c -D__TARGET_TOFINO__=1 --target tofino -g --arch tna -o /opt/p4tg traffic_gen.p4

      - name: Tofino2 CI
        run: cd P4-Implementation && sudo -E /open-p4studio/install/bin/bf-p4c -D__TARGET_TOFINO__=2 --target tofino2 -g --arch t2na -o /opt/p4tg traffic_gen.p4
