name: Controller build

on:
  push:
    branches: [ "main", "nightly"]
  pull_request:
    branches: [ "main", "nightly" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Docker tag based on branch
      id: vars
      run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          echo "tag=latest" >> $GITHUB_OUTPUT
        elif [ "${{ github.ref_name }}" = "nightly" ]; then
          echo "tag=nightly" >> $GITHUB_OUTPUT
        else
          echo "tag=dev" >> $GITHUB_OUTPUT
        fi

    - name: Read version from VERSION.md
      id: version
      run: |
        version=$(cat VERSION.md | tr -d ' \n')
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: Configuration\ GUI/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('Configuration GUI/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Build frontend
      run: cd Configuration\ GUI && npm install && npm run build
      env:
        CI: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    #- name: Controller Build with Buildx and Cache
    #  run: |
    #    docker buildx build \
    #      --cache-from=type=registry,ref=unituekn/p4tg-controller:buildcache \
    #      --cache-to=type=registry,ref=unituekn/p4tg-controller:buildcache,mode=max \
    #      --tag unituekn/p4tg-controller:${{ steps.vars.outputs.tag }} \
    #      --tag unituekn/p4tg-controller:${{ steps.version.outputs.version }} \
    #      --file Controller/Dockerfile \
    #      --push \
    #      .
    - name: Controller Build with Buildx (no cache, debug)
      run: |
        docker buildx build \
          --no-cache \
          --tag unituekn/p4tg-controller:${{ steps.vars.outputs.tag }} \
          --tag unituekn/p4tg-controller:${{ steps.version.outputs.version }} \
          --file Controller/Dockerfile \
          --push \
          .    
